config/routes.rb
Rails.application.routes.draw do
  get 'donations/index'

  get 'donations/new'

  get 'donations/create'

  get 'group_applications/index'

  get 'group_applications/new'

  get 'group_applications/update'

  get 'conference_options/new'

  get 'conference_options/create'

  get 'conference_options/index'

  get 'conference_options/show'

  get 'conference_options/edit'

  get 'conference_options/update'

  get 'conferences/new'

  get 'conferences/create'

  get 'conferences/edit'

  get 'conferences/update'

  get 'conferences/show'

  get 'conferences/index'

  get 'members/new'

  get 'members/create'

  get 'members/index'

  get 'members/edit'

  get 'members/update'

  get 'members/destroy'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'home#index'

  get 'announcement' => 'home#announcement'
  get 'registration' => 'users#new'
  get 'tours'        => 'home#tours'
  get 'contact'      => 'home#contact'
  get 'login'        => 'sessions#new'
  post 'login'       => 'sessions#create'
  get 'logout'       => 'sessions#destroy'
  get 'applications' => 'group_applications#index'
  get 'donations'    => 'donations#index'

  resources :users
  resources :members
  resources :groups, only: [:edit, :update, :destroy]
  resources :conferences
  resources :conference_options
  resources :group_applications,  only: [:index, :new, :create]
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:index, :new, :create, :edit, :update]

end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  def new
  end

  def create
  end

  def index
  	@groups = current_user.groups.paginate(page: params[:page]).order('created_at DESC')
  end
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/create.html.erb
<h1>Donations#create</h1>
<p>Find me in app/views/donations/create.html.erb</p>

app/views/donations/index.html.erb
<div id="donations" class="table-responsive">
	<%= will_paginate @groups %>
	<table class="table table-hover table-condensed table-striped table-bordered">
		<thead>
			<tr>
				<th>組別</th>
				<th>人數</th>
				<th>繳費金額</th>
				<th>刪除</th>
				<th>繳費狀態</th>
			</tr>
		</thead>
		<tbody>
			<% @groups.each do |group| %>
					<tr id="group_<%= group.id %>">
						<td><%= group.id %></td>
						<td><%= link_to group.no_of_applicants, "#", remote: true  %></td>
						<td><%= group.donate_amount %></td>

						<td><%= link_to '刪除', group_path(group), method: :delete, data: {confirm: "確認刪除?"}, remote: true  %></td>
						<% if group.edible %>
							<td><%= link_to "繳費", "#" %></td>
						<% else %>
							<td>已完成繳費</td>
						<% end %>
					</tr>
				<% end %>
			</tbody>
	</table>
	<%= will_paginate @groups %>
</div>

app/views/donations/new.html.erb
<h1>Donations#new</h1>
<p>Find me in app/views/donations/new.html.erb</p>