config/routes.rb
Rails.application.routes.draw do
  get 'donations/index'

  get 'donations/new'

  get 'donations/create'

  get 'group_applications/index'

  get 'group_applications/new'

  get 'group_applications/update'

  get 'conference_options/new'

  get 'conference_options/create'

  get 'conference_options/index'

  get 'conference_options/show'

  get 'conference_options/edit'

  get 'conference_options/update'

  get 'conferences/new'

  get 'conferences/create'

  get 'conferences/edit'

  get 'conferences/update'

  get 'conferences/show'

  get 'conferences/index'

  get 'members/new'

  get 'members/create'

  get 'members/index'

  get 'members/edit'

  get 'members/update'

  get 'members/destroy'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'home#index'

  get 'announcement' => 'home#announcement'
  get 'registration' => 'users#new'
  get 'tours'        => 'home#tours'
  get 'contact'      => 'home#contact'
  get 'login'        => 'sessions#new'
  post 'login'       => 'sessions#create'
  get 'logout'       => 'sessions#destroy'
  get 'applications' => 'group_applications#index'
  get 'donations'    => 'donations#index'

  resources :users
  resources :members
  resources :groups, only: [:edit, :update, :destroy]
  resources :conferences
  resources :conference_options
  resources :group_applications,  only: [:index, :new, :create]
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:index, :new, :create, :edit, :update]

end

app/controllers/group_applications_controller.rb
class GroupApplicationsController < ApplicationController
  def index
  end

  def new
  end

  def update
  end
end

app/helpers/group_applications_helper.rb
module GroupApplicationsHelper
end

app/views/group_applications/index.html.erb
<% provide(:title, "Sign in") %>
<div class="row" id="application-panel">
	<div class="col-md-4 col-md-offset-1" id="group-application-panel">
		<div class="panel panel-success">
			<div class="panel-heading">Upload excel files</div>
			<div class="panel-body">
				<%= form_for :group_applications, url: group_applications_new_path do |f| %>
					<div class="form-group">
						<%= f.label :group_files, "請選擇你要上傳的文件", class: "control-label" %>
						<%= f.file_field :group_files, class: "form-control", tabindex:"1" %>
					</div>
					<div class="form-group">
						<%= f.submit "Submit", class: "btn  btn-success", tabindex:"3" %>
					</div>
				<% end %>
			</div>
		</div>
	</div>
	<div class="col-md-1" id="applications-divider"></div>
	<div class="col-md-4 col-md-offset-1" id="single-application-panel">
	<div class="panel panel-success">
			<div class="panel-heading">Single application</div>
			<div class="panel-body">
				<%= link_to "單個人位報名", new_member_path, class:"btn  btn-warning", id: "new-member-link", remote: true %>
			</div>
		</div>
	</div>
</div>

app/views/group_applications/new.html.erb
<h1>GroupApplications#new</h1>
<p>Find me in app/views/group_applications/new.html.erb</p>

app/views/group_applications/update.html.erb
<h1>GroupApplications#update</h1>
<p>Find me in app/views/group_applications/update.html.erb</p>