config/routes.rb
Rails.application.routes.draw do
  get 'donations/index'

  get 'donations/new'

  get 'donations/create'

  get 'group_applications/index'

  get 'group_applications/new'

  get 'group_applications/update'

  get 'conference_options/new'

  get 'conference_options/create'

  get 'conference_options/index'

  get 'conference_options/show'

  get 'conference_options/edit'

  get 'conference_options/update'

  get 'conferences/new'

  get 'conferences/create'

  get 'conferences/edit'

  get 'conferences/update'

  get 'conferences/show'

  get 'conferences/index'

  get 'members/new'

  get 'members/create'

  get 'members/index'

  get 'members/edit'

  get 'members/update'

  get 'members/destroy'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'home#index'

  get 'announcement' => 'home#announcement'
  get 'registration' => 'users#new'
  get 'tours'        => 'home#tours'
  get 'contact'      => 'home#contact'
  get 'login'        => 'sessions#new'
  post 'login'       => 'sessions#create'
  get 'logout'       => 'sessions#destroy'
  get 'applications' => 'group_applications#index'
  get 'donations'    => 'donations#index'

  resources :users
  resources :members
  resources :groups, only: [:edit, :update, :destroy]
  resources :conferences
  resources :conference_options
  resources :group_applications,  only: [:index, :new, :create]
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:index, :new, :create, :edit, :update]

end

app/views/layouts/_application_navbar.html.erb
<div class="container">
	<div>
	<h1>報名流程</h1>
</div>
<div class="btn-group btn-group-justified application-navbar" role="group" aria-label="...">
  <div class="btn-group" role="group">
    <%= link_to "1-報名", applications_path, class: "btn btn-primary btn-lg" %>
  </div>
  <div class="btn-group" role="group">
    <%= link_to "2-繳費", donations_path, class: "btn btn-warning btn-lg" %>
  </div>
  <div class="btn-group" role="group">
    <%= link_to "3-確認報名資料", members_path, class: "btn btn-success btn-lg" %>
  </div>
</div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav class="pull-left">
    <ul>
      <li>&copy; <%= copyright_notice_year_range() %> <%= link_to "The Church in Taipei, Inc.", 'http://www.churchintaipei.org', class:"footer-font" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-default">
  <div class="container-fluid container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "ICSC", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if logged_in?  %>
        <ul class="nav navbar-nav navbar-right">
          <li class="<%= 'active' if current_page?(tours_path) %>"><%= link_to 'Tours', tours_path %></li>
          <li class="<%= 'active' if current_page?(applications_path) %>"><%= link_to 'Application', applications_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.username %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Profile</a></li>
              <li><%= link_to 'Settings', edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to 'Log out', logout_path %></li>
            </ul>
          </li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li class="<%= 'active' if current_page?(tours_path) %>">
            <%= link_to tours_path, :class => 'menu' do %>Tours <span class="sr-only">(current)</span>
          <% end %>
        </li>
        <li class="<%= 'active' if current_page?(announcement_path) %>"><%= link_to 'Announcement', announcement_path %></li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Language <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">English</a></li>
              <li><%= link_to '中文', "#" %></li>
            </ul>
          </li>
          <li class="<%= 'active' if current_page?(login_path) %>"><%= link_to 'Sign in', login_path %></li>
        </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_root_navbar.html.erb
<div class="container">
	<div>
	<h1>超級管理員</h1>
</div>
<div class="btn-group btn-group-justified application-navbar" role="group" aria-label="...">
	<div class="btn-group" role="group">
    <%= link_to "特會管理", new_member_path, class: "btn btn-info btn-lg" %>
  </div>
  <div class="btn-group" role="group">
    <%= link_to "註冊用戶管理", new_member_path, class: "btn btn-primary btn-lg" %>
  </div>
  <div class="btn-group" role="group">
    <%= link_to "報名會員管理", new_member_path, class: "btn btn-warning btn-lg" %>
  </div>
  <div class="btn-group" role="group">
    <%= link_to "確認報名資料", new_member_path, class: "btn btn-success btn-lg" %>
  </div>
</div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= full_title(yield(:title)) %></title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= favicon_link_tag 'favicon.ico' %>
	  <%= csrf_meta_tags %>
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	  <%= render 'layouts/shim' %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<% if logged_in? && current_user.role == "normal" && !current_page?(root_path) && !current_page?(tours_path) %>
			<%= render 'layouts/application_navbar' %>
		<% elsif logged_in? && current_user.role == "root"
			 %>
			 <%= render 'layouts/root_navbar' %>
		<% end %>
	  <div class="container">
	  	<% flash.each do | message_type, message | %>
	  		<div class="alert alert-<%= message_type %>"><%= message %></div>
			<% end %>
	  </div>
		<div class="container">
			<%= yield %>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>