config/routes.rb
Rails.application.routes.draw do
  get 'donations/index'

  get 'donations/new'

  get 'donations/create'

  get 'group_applications/index'

  get 'group_applications/new'

  get 'group_applications/update'

  get 'conference_options/new'

  get 'conference_options/create'

  get 'conference_options/index'

  get 'conference_options/show'

  get 'conference_options/edit'

  get 'conference_options/update'

  get 'conferences/new'

  get 'conferences/create'

  get 'conferences/edit'

  get 'conferences/update'

  get 'conferences/show'

  get 'conferences/index'

  get 'members/new'

  get 'members/create'

  get 'members/index'

  get 'members/edit'

  get 'members/update'

  get 'members/destroy'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'home#index'

  get 'announcement' => 'home#announcement'
  get 'registration' => 'users#new'
  get 'tours'        => 'home#tours'
  get 'contact'      => 'home#contact'
  get 'login'        => 'sessions#new'
  post 'login'       => 'sessions#create'
  get 'logout'       => 'sessions#destroy'
  get 'applications' => 'group_applications#index'
  get 'donations'    => 'donations#index'

  resources :users
  resources :members
  resources :groups, only: [:edit, :update, :destroy]
  resources :conferences
  resources :conference_options
  resources :group_applications,  only: [:index, :new, :create]
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:index, :new, :create, :edit, :update]

end

app/models/member.rb
class Member < ActiveRecord::Base
	attr_accessor :name
	belongs_to :user
	belongs_to :group

	GENDER_OPTION = %w(男 女 M F)
	validates :gender, inclusion: {in: GENDER_OPTION}

	validates :age, numericality: {only_integer: true, greater_than: 0, less_than: 100}, allow_blank: true
	validates :country, presence: true
	validates :church, presence:true

	# VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	# validates :email,	format: { with: VALID_EMAIL_REGEX }

	CONFERENCE_OPTION = %W(OC BC AC OB OC)
	validates :conference_option, inclusion: {in: CONFERENCE_OPTION}

	def name
		if !self.chinese_name.blank?
			chinese_name
		else
			"#{firstname} #{lastname}"
		end
	end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_group, only: [:new, :create]

  def new
    @member = @group.members.build
  end

  def create
    @member = @group.members.build(member_params)

      respond_to do |format|
      if @member.save
        format.html {  
          single_application_update(@member)
          redirect_to @member,  notice: 'Member was successfully created.'
        }

        format.json {
          single_application_update(@member)
          render action: 'show', status: :created, location: @member
        }

        format.js {
          single_application_update(@member)
          render action: 'show', status: :created, location: @member
        }    
      else
        format.html { render "new" }
        format.json { render json: @member.errors, status: :unprocessable_entity}
        format.js   { render json: @member.errors, status: :unprocessable_entity}
      end
    end
  end

  def index
    @members = current_user.members.where(:enabled => true).paginate(page: params[:page]).order('created_at DESC')
  end

  def show
    @member = Member.find(params[:id])

    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit
    @member = Member.find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    @member = Member.find(params[:id])

    respond_to do |format|
      if @member.update_attributes(member_params)
        @member.group.update_attribute(:donate_amount, donate_amount(@member.conference_option))
        format.html { redirect_to members_path, notice: "Member was successfully updated."}
        format.json { head :no_content }
        format.js
      else
        format.html { render action: "edit" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def destroy
  end


  private
    def member_params
      params.require(:member).permit(:firstname, :lastname, :chinese_name, :gender, :age, :country, :church, :pick_up, :arrived_date, :arrived_time, :arrived_airport, :arrived_flight_no, :drop_off, :departed_date, :departed_time, :departed_airport, :departed_flight_no, :conference_option, :comments)
    end

    def set_group
      @group = current_user.groups.build(user_id: current_user.id)
    end

    def single_application_update(member)
      member.group.update_attribute(:no_of_applicants, 1)
      member.group.update_attribute(:donate_amount, donate_amount(@member.conference_option))
    end

    def donate_amount(conference_option)
      if conference_option == "OC"
        100
      elsif conference_option == "BC" || conference_option == "AC"
        250
      else
        150
      end    
    end   
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<div class="row" id="single-application-form">
	<div class="col-md-8 col-md-offset-2" >
		<div class="panel panel-success">
			<div class="panel-heading">Single application From</div>
			<div class="panel-body">
				<%= form_for @member, html: {role: :form, 'data-model': 'member', class: 'form-horizontal'} do |f| %>
					<%= render 'shared/member_error_messages' %>
					<fieldset>
						<div class="form-group required">
							<%= f.label :firstname, "First Name", class: "col-sm-3 control-label required" %>
							<div class="col-sm-5">
									<%= f.text_field :firstname, class: "form-control", placeholder: "ex: Tobias or 張", autofocus:"true", required: "true" %>
							</div>
						</div>
						<div class="form-group  required">
							<%= f.label :lastname, "Last Name", class: "col-sm-3 control-label" %>
							<div class="col-sm-5">
									<%= f.text_field :lastname, class: "form-control", placeholder: "ex Chang or 顯主", required: "true" %>
							</div>
						</div>
						<div class="form-group">
							<%= f.label :chinese_name, "Chinese Name", class: "col-sm-3 control-label" %>
							<div class="col-sm-5">
									<%= f.text_field :chinese_name, class: "form-control", placeholder: "ex 張顯主" %>
							</div>
						</div>
						<div class="form-group required">
							<%= f.label :gender, "Gender", class: "col-sm-3 control-label" %>
							<div class="col-sm-5">
								<label class="radio-inline">
				         	<%= f.radio_button :gender, "M", checked: "checked" %> Male
				        </label>
				        <label class="radio-inline">
				         	<%= f.radio_button :gender, "F" %> Female
				        </label>
			        </div>
		      	</div>
		      	<div class="form-group">
							<%= f.label :age, "Age", class: "col-sm-3 control-label" %>
							<div class="col-sm-5">
									<%= f.text_field :age, class: "form-control", placeholder: "ex: USA or 中國" %>
							</div>
						</div>
						<div class="form-group  required">
							<%= f.label :country, "Country", class: "col-sm-3 control-label" %>
							<div class="col-sm-5">
									<%= f.text_field :country, class: "form-control", placeholder: "ex: USA or 中國", required: "true" %>
							</div>
						</div>
						<div class="form-group  required">
							<%= f.label :church, "Church", class: "col-sm-3 control-label" %>
							<div class="col-sm-5">
									<%= f.text_field :church, class: "form-control", placeholder: "ex: Anaheim or 上海", required: "true" %>
							</div>
						</div>
						<div class="form-group">
							<%= f.label :email, "Email", class: "col-sm-3 control-label" %>
							<div class="col-sm-5">
									<%= f.text_field :email, class: "form-control", placeholder: "ex: lovelord@gmail.com" %>
							</div>
						</div>
						<div class="form-group required">
							<%= f.label :pick_up, "Need pick up", class: "col-sm-3 control-label" %>
							<div class="col-sm-5">
								<label class="radio-inline">
				         	<%= f.radio_button :pick_up, "Y", checked: "checked" %> Yes
				        </label>
				        <label class="radio-inline">
				         	<%= f.radio_button :pick_up, "N" %> No
				        </label>
			        </div>
		      	</div>
		      	<div class="arrived_attributes">
		      		<div class="form-group">
								<%= f.label :arrvied_date, "Arrived date", class: "col-sm-3 control-label" %>
								<div class="col-sm-5">
										<%= f.date_field :arrived_date, class: "form-control" %>
								</div>
							</div>
							<div class="form-group">
								<%= f.label :arrvied_time, "Arrived time", class: "col-sm-3 control-label" %>
								<div class="col-sm-5">
										<%= f.text_field :arrived_time, class: "form-control", placeholder: "ex: 21:30" %>
								</div>
							</div>
							<div class="form-group">
								<%= f.label :arrvied_airport, "Arrived airport", class: "col-sm-3 control-label" %>
								<div class="col-sm-5">
										<%= f.text_field :arrived_airport, class: "form-control", placeholder: "ex: TPE T1" %>
								</div>
							</div>
							<div class="form-group">
								<%= f.label :arrvied_flight_no, "Arrived flight NO.", class: "col-sm-3 control-label" %>
								<div class="col-sm-5">
										<%= f.text_field :arrived_flight_no, class: "form-control", placeholder: "ex: CX451" %>
								</div>
							</div>
		      	</div>

						<div class="form-group required">
							<%= f.label :drop_off, "Need drop off", class: "col-sm-3 control-label" %>
							<div class="col-sm-5">
								<label class="radio-inline">
				         	<%= f.radio_button :drop_off, "Y", checked: "checked" %> Yes
				        </label>
				        <label class="radio-inline">
				         	<%= f.radio_button :drop_off, "N" %> No
				        </label>
			        </div>
		      	</div>
		      	<div class="form-group">
							<%= f.label :departed_date, "Departed date", class: "col-sm-3 control-label" %>
							<div class="col-sm-5">
									<%= f.date_field :departed_date, class: "form-control" %>
							</div>
						</div>
						<div class="form-group">
							<%= f.label :departed_time, "Departed time", class: "col-sm-3 control-label" %>
							<div class="col-sm-5">
									<%= f.text_field :departed_time, class: "form-control", placeholder: "ex: 21:30" %>
							</div>
						</div>
						<div class="form-group">
							<%= f.label :departed_airport, "Departed airport", class: "col-sm-3 control-label" %>
							<div class="col-sm-5">
									<%= f.text_field :departed_airport, class: "form-control", placeholder: "ex: TPE T1" %>
							</div>
						</div>
						<div class="form-group">
							<%= f.label :departed_flight_no, "Departed flight NO.", class: "col-sm-3 control-label" %>
							<div class="col-sm-5">
									<%= f.text_field :departed_flight_no, class: "form-control", placeholder: "ex: CX450" %>
							</div>
						</div>
						<div class="form-group">
							<%= f.label :conference_option, "Conference option", class: "col-sm-3 control-label" %>
							<div class="col-sm-5">
									<%= f.collection_select(:conference_option, ConferenceOption.all, :short_code, :option_name, {prompt: "Select a option"}, {class: "form-control"}) %>
							</div>
						</div>
						<div class="form-group required">
							<%= f.label :hospitality, "Need hospitality", class: "col-sm-3 control-label" %>
							<div class="col-sm-5">
								<label class="radio-inline">
				         	<%= f.radio_button :hospitality, true, checked:"checked" %> Yes
				        </label>
				        <label class="radio-inline">
				         	<%= f.radio_button :hospitality, false %> No
				        </label>
			        </div>
		      	</div>
						<div class="form-group">
							<%= f.label :comments, "Comments", class: "col-sm-3 control-label" %>
							<div class="col-sm-5">
									<%= f.text_area :comments, class: "form-control", placeholder: "Comments" %>
							</div>
						</div>
						<div class="form-group">
							<div class="col-sm-offset-3 col-sm-3">
									<%= f.submit class: "btn btn-success" %> <%= link_to "Back", :back, class: "btn btn-warning" %>
							</div>
						</div>
					</fieldset>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/members/_member.html.erb
<tbody>
	<tr>
		<td><%= member.name %></td>
		<td><%= member.gender %></td>
		<td><%= member.pick_up %></td>
		<td><%= member.hospitality %></td>
		<td><%= member.conference_option %></td>
		<td><%= member.donated %></td>
		<td><%= link_to '查看', member_path(member), remote: true  %></td>
		<td><%= link_to '編輯', edit_member_path(member), remote: true  %></td>
	</tr>
</tbody>

app/views/members/create.html.erb
<h1>Members#create</h1>
<p>Find me in app/views/members/create.html.erb</p>

app/views/members/create.js.erb
<% if @member.errors.count == 0 %>

	$('#single-application-form').hide();

<% else %>
	$('#single-application-form').hide();
<!-- 	$('.new_member').remove();
	$('#new_member_link').after('<%= j render("form") %>'); -->

<% end %>

app/views/members/destroy.html.erb
<h1>Members#destroy</h1>
<p>Find me in app/views/members/destroy.html.erb</p>

app/views/members/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

app/views/members/edit.js.erb
$('#members').hide().after('<%= j render("form") %>');

app/views/members/index.html.erb
<div id="members" class="table-responsive">
	<%= will_paginate %>
	<table class="table table-hover table-condensed table-striped table-bordered">
		<thead>
			<tr>
				<th>序號</th>
				<th>姓名</th>
				<th>性別</th>
				<th>需要接機</th>
				<th>需要接待</th>
				<th>特會選項</th>
				<th>繳費狀態</th>
				<th>查看</th>
				<th>編輯</th>
			</tr>
		</thead>
		<tbody>
			<% @members.each do |member| %>
					<tr class="<%= member.donated? ? "success" : "info" %>">
						<td><%= member.no %></td>
						<td><%= member.name %></td>
						<td><%= member.gender %></td>

						<% if member.pick_up %>
							<td>Y</td>
						<% else %>
							<td>N</td>
						<% end %>

						<td><%= member.hospitality %></td>
						<td><%= member.conference_option %></td>

						<% if member.donated %>
							<td>Y</td>
						<% else %>
							<td>N</td>
						<% end %>
						
						<td><%= link_to '查看', member_path(member), remote: true  %></td>
						<td><%= link_to '編輯', edit_member_path(member), remote: true  %></td>
					</tr>
				<% end %>
			</tbody>
	</table>
	<%= will_paginate %>
</div>

app/views/members/new.html.erb
<% provide(:title, "Single application") %>
<%= render 'form' %>

<%= link_to 'Back', applications_path %>

app/views/members/new.js.erb
$('#application-panel').hide().after('<%= j render("form") %>');

app/views/members/show.js.erb
$('#members').hide().after('<%= j render("show") %>');

app/views/members/update.html.erb
<h1>Members#update</h1>
<p>Find me in app/views/members/update.html.erb</p>

app/views/members/update.js.erb
$('#single-application-form').hide().after('<%= j render("members/index") %>');